import { NgModule } from '@angular/core';
// import { CdkTableModule } from '@angular/cdk/table';
import { LayoutModule } from '@angular/cdk/layout';
import { AmazingTimePickerModule } from 'amazing-time-picker'; // this line you need

import {
  // MatAutocompleteModule,
  // MatButtonToggleModule,
  // MatCardModule,
  MatToolbarModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatNativeDateModule, 
  // MatDividerModule,
  // MatExpansionModule,
  // MatGridListModule,
  // MatIconModule,
  MatInputModule,
  // MatListModule,
  MatMenuModule,
  // MatNativeDateModule,
  MatPaginatorModule,
  // MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  // MatRippleModule,
  MatSelectModule,
  // MatSidenavModule,
  // MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  // MatSortModule,
  // MatStepperModule,
  MatTableModule,
  MatTabsModule,
  // MatToolbarModule,
  MatTooltipModule,
  MatBadgeModule
} from '@angular/material';
import { RedPipe } from '../../utils/pipes/four-hours/red.pipe';
import { SortCabPipe } from '../../utils/pipes/sort-cab/sort-cab.pipe';
import { DateFormatPipe } from '../../utils/pipes/date-format/date-format.pipe';
import { StartTimePipe } from '../../utils/pipes/startTime/start-time.pipe';

@NgModule({
  declarations:[
    RedPipe,
    SortCabPipe,
    DateFormatPipe,
    StartTimePipe
    ],
  imports: [
    LayoutModule,
    // MatAutocompleteModule,
    MatButtonModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    // MatButtonToggleModule,
    // MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    // MatDividerModule,
    // MatExpansionModule,
    // MatGridListModule,
    // MatIconModule,
    MatInputModule,
    // MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    // MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    // MatRippleModule,
    MatSelectModule,
    // MatSidenavModule,
    // MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    // MatSortModule,
    // MatStepperModule,
    MatTableModule,
    MatTabsModule,
    // MatToolbarModule,
    MatTooltipModule,
    AmazingTimePickerModule,
    MatBadgeModule
  ],
  exports: [
    LayoutModule,
    // CdkTableModule,
    // MatAutocompleteModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatButtonModule,
    // MatButtonToggleModule,
    // MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    // MatStepperModule,
    MatDatepickerModule,
    MatDialogModule,
    // MatDividerModule,
    // MatExpansionModule,
    // MatGridListModule,
    // MatIconModule,
    MatInputModule,
    // MatListModule,
    MatMenuModule,
    // MatNativeDateModule,
    MatPaginatorModule,
    // MatProgressBarModule,
    MatProgressSpinnerModule,
    MatNativeDateModule, 
    MatRadioModule,
    // MatRippleModule,
    MatSelectModule,
    // MatSidenavModule,
    // MatSliderModule,
    // MatSlideToggleModule,
    MatSnackBarModule,
    // MatSortModule,
    MatTableModule,
    MatTabsModule,
    // MatToolbarModule,
    MatTooltipModule,
    RedPipe,
    SortCabPipe,
    DateFormatPipe,
    StartTimePipe,
    AmazingTimePickerModule,
    MatBadgeModule
    
  ],
})

export class MaterialModule { }


